#!/usr/bin/env python

import pyrealsense2 as rs
import numpy as np
import cv2
import rospy
from geometry_msgs.msg import Pose, Point
from sensor_msgs.msg import Image
from cv_bridge import CvBridge,CvBridgeError

# Configure depth and color streams


def detect():

    pub = rospy.Publisher('camera_rect/image_rect',Image, queue_size=1)
    rospy.init_node('realsense_detect')
    rate = rospy.Rate(60)

    cam = cv2.VideoCapture(0)

    # Start streaming

    while not rospy.is_shutdown():
        ret,frame = cam.read()
        bridge=CvBridge()
        msg = bridge.cv2_to_imgmsg(frame,encoding="bgr8")
        pub.publish(msg)
        rate.sleep()

if __name__ =='__main__':
    try:
        detect()
    except rospy.ROSInterruptException:
        pass