#!/usr/bin/env python
import rospy
from cv_bridge import CvBridge
from sensor_msgs.msg import Image, CameraInfo, CompressedImage
import cv2
import tf
import numpy as np
from apriltags_ros.msg import AprilTagDetectionArray
from geometry_msgs.msg import Pose, Point


class TagDetect:
       
    def __init__(self):

        # Baxter's right hand camera
        self.right_camera = rospy.Subscriber("/cameras/right_hand_camera/image", Image, self.baxter_cam)
        # Baxter's left hand camera
        # self.right_camera = rospy.Subscriber("/cameras/left_hand_camera/image", Image, self.baxter_cam)


        # Publishes raw and color images from the Baxter
        self.raw_image_pub = rospy.Publisher("/image_raw", Image, queue_size = 1)
        self.color_image_pub = rospy.Publisher("/image_color", Image, queue_size = 1)


        # Publishes image_rect that apriltag_ros will receive
        self.image_rect_sub = rospy.Subscriber( "/image_rect", Image, self.rect_image_callback)
        self.image_rect_pub= rospy.Publisher( "/camera_rect/image_rect", Image, queue_size = 1)

        # Calibration Matrix
        self.cal_sub = rospy.Subscriber("/cameras/right_hand_camera/camera_info_std", CameraInfo, self.cal_n_info_pub)
        self.cal_pub =  rospy.Publisher("/camera/camera_info", CameraInfo, queue_size = 1)


        # Publishes camera_info that apriltag_ros will receive
        self.caminfo_pub= rospy.Publisher("/camera_info", CameraInfo, queue_size = 1)
        self.caminfo_rect_pub= rospy.Publisher("/camera_rect/camera_info", CameraInfo, queue_size = 1)





        # Subscribe to the april tag classification data stream
        self.apriltags = rospy.Subscriber("/tag_detections", AprilTagDetectionArray, self.apriltag_callback)  


    def baxter_cam(self, data):
        self.raw_image_pub.publish(data)
        self.color_image_pub.publish(data)


    def rect_image_callback(self, data):
        self.image_rect_pub.publish(data)

        
    def apriltag_callback(self, data):

        pose = Pose()
   
    # Calibrate and publish Camera Info for apriltag_ros
    def cal_n_info_pub(self, data):

        self.cal_pub.publish(data)
        self.caminfo_pub.publish(data)
        self.caminfo_rect_pub.publish(data)
 

# Main Function
if __name__ == "__main__":

    rospy.init_node("TagDetect")

    # create object
    TagDetect()

    # Keep the thread alive by spinning
    rospy.spin()